brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
    - homebrew/dupes
    - homebrew/versions
    - homebrew/binary
    - peco/peco
    - motemen/ghq
    - caskroom/cask
  install_packages:
    - brew-cask
    - coreutils
    - findutils
    - bash
    - vim
    - tmux
    - git
    - hub
    - ghq
    - wget
    - rsync
    - curl
    - tree
    - openssl
    - libyaml
    - readline
    - markdown
    - jq
    - peco
    - ctags
    - z
    - rbenv
    - ruby-build
  install_apps:
    - google-chrome
    - firefox
    - iterm2
    - skype
    - slack
    - google-japanese-ime
    - macvim
